// constants/currencies.ts

export interface Currency {
  code: string;
  name: string;
  symbol: string;
}

export const CURRENCIES: Currency[] = [
  { code: 'USD', name: 'US Dollar', symbol: '$' },
  { code: 'EUR', name: 'Euro', symbol: '€' },
  { code: 'GBP', name: 'British Pound', symbol: '£' },
  { code: 'JPY', name: 'Japanese Yen', symbol: '¥' },
  { code: 'CAD', name: 'Canadian Dollar', symbol: 'CA$' },
  { code: 'AUD', name: 'Australian Dollar', symbol: 'A$' },
  { code: 'CHF', name: 'Swiss Franc', symbol: 'CHF' },
  { code: 'CNY', name: 'Chinese Yuan', symbol: '¥' },
  { code: 'INR', name: 'Indian Rupee', symbol: '₹' },
  { code: 'BRL', name: 'Brazilian Real', symbol: 'R$' },
  { code: 'MXN', name: 'Mexican Peso', symbol: 'MX$' },
  { code: 'SGD', name: 'Singapore Dollar', symbol: 'S$' },
  { code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK$' },
  { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr' },
  { code: 'SEK', name: 'Swedish Krona', symbol: 'kr' },
  { code: 'DKK', name: 'Danish Krone', symbol: 'kr' },
  { code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ$' },
  { code: 'ZAR', name: 'South African Rand', symbol: 'R' },
  { code: 'AED', name: 'UAE Dirham', symbol: 'د.إ' },
  { code: 'SAR', name: 'Saudi Riyal', symbol: '﷼' },
  { code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'KD' },
  { code: 'QAR', name: 'Qatari Riyal', symbol: 'QR' },
  { code: 'EGP', name: 'Egyptian Pound', symbol: 'E£' },
  { code: 'NGN', name: 'Nigerian Naira', symbol: '₦' },
  { code: 'KES', name: 'Kenyan Shilling', symbol: 'KSh' },
  { code: 'GHS', name: 'Ghanaian Cedi', symbol: 'GH₵' },
  { code: 'TZS', name: 'Tanzanian Shilling', symbol: 'TSh' },
  { code: 'UGX', name: 'Ugandan Shilling', symbol: 'USh' },
  { code: 'MAD', name: 'Moroccan Dirham', symbol: 'MAD' },
  { code: 'PKR', name: 'Pakistani Rupee', symbol: '₨' },
  { code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳' },
  { code: 'LKR', name: 'Sri Lankan Rupee', symbol: 'Rs' },
  { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp' },
  { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM' },
  { code: 'THB', name: 'Thai Baht', symbol: '฿' },
  { code: 'VND', name: 'Vietnamese Dong', symbol: '₫' },
  { code: 'PHP', name: 'Philippine Peso', symbol: '₱' },
  { code: 'KRW', name: 'South Korean Won', symbol: '₩' },
  { code: 'TWD', name: 'Taiwan Dollar', symbol: 'NT$' },
  { code: 'TRY', name: 'Turkish Lira', symbol: '₺' },
  { code: 'RUB', name: 'Russian Ruble', symbol: '₽' },
  { code: 'PLN', name: 'Polish Złoty', symbol: 'zł' },
  { code: 'CZK', name: 'Czech Koruna', symbol: 'Kč' },
  { code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft' },
  { code: 'RON', name: 'Romanian Leu', symbol: 'lei' },
  { code: 'UAH', name: 'Ukrainian Hryvnia', symbol: '₴' },
  { code: 'ILS', name: 'Israeli Shekel', symbol: '₪' },
  { code: 'CLP', name: 'Chilean Peso', symbol: 'CL$' },
  { code: 'COP', name: 'Colombian Peso', symbol: 'CO$' },
  { code: 'ARS', name: 'Argentine Peso', symbol: 'AR$' },
  { code: 'PEN', name: 'Peruvian Sol', symbol: 'S/.' },
  { code: 'DZD', name: 'Algerian Dinar', symbol: 'DA' },
  { code: 'TND', name: 'Tunisian Dinar', symbol: 'DT' },
  { code: 'ETB', name: 'Ethiopian Birr', symbol: 'Br' },
  { code: 'XOF', name: 'West African CFA Franc', symbol: 'CFA' },
  { code: 'XAF', name: 'Central African CFA Franc', symbol: 'FCFA' },
  { code: 'BHD', name: 'Bahraini Dinar', symbol: 'BD' },
  { code: 'OMR', name: 'Omani Rial', symbol: 'ر.ع.' },
  { code: 'JOD', name: 'Jordanian Dinar', symbol: 'JD' },
  { code: 'GEL', name: 'Georgian Lari', symbol: '₾' },
  { code: 'KZT', name: 'Kazakhstani Tenge', symbol: '₸' },
  { code: 'BGN', name: 'Bulgarian Lev', symbol: 'лв' },
  { code: 'ISK', name: 'Icelandic Króna', symbol: 'kr' },
  { code: 'BWP', name: 'Botswana Pula', symbol: 'P' },
  { code: 'ZMW', name: 'Zambian Kwacha', symbol: 'ZK' },
  { code: 'RWF', name: 'Rwandan Franc', symbol: 'RF' },
];

export const COUNTRY_CURRENCY_MAP: Record<string, string> = {
  'united states': 'USD', 'usa': 'USD', 'us': 'USD',
  'united kingdom': 'GBP', 'uk': 'GBP', 'britain': 'GBP',
  'canada': 'CAD', 'australia': 'AUD', 'new zealand': 'NZD',
  'germany': 'EUR', 'france': 'EUR', 'italy': 'EUR', 'spain': 'EUR',
  'netherlands': 'EUR', 'portugal': 'EUR', 'ireland': 'EUR',
  'belgium': 'EUR', 'austria': 'EUR', 'greece': 'EUR',
  'finland': 'EUR', 'luxembourg': 'EUR', 'malta': 'EUR',
  'japan': 'JPY', 'china': 'CNY', 'india': 'INR', 'brazil': 'BRL',
  'mexico': 'MXN', 'singapore': 'SGD', 'hong kong': 'HKD',
  'norway': 'NOK', 'sweden': 'SEK', 'denmark': 'DKK',
  'switzerland': 'CHF', 'south africa': 'ZAR',
  'uae': 'AED', 'united arab emirates': 'AED',
  'saudi arabia': 'SAR', 'kuwait': 'KWD', 'qatar': 'QAR',
  'egypt': 'EGP', 'nigeria': 'NGN', 'kenya': 'KES',
  'ghana': 'GHS', 'tanzania': 'TZS', 'uganda': 'UGX',
  'morocco': 'MAD', 'pakistan': 'PKR', 'bangladesh': 'BDT',
  'sri lanka': 'LKR', 'indonesia': 'IDR', 'malaysia': 'MYR',
  'thailand': 'THB', 'vietnam': 'VND', 'philippines': 'PHP',
  'south korea': 'KRW', 'taiwan': 'TWD', 'turkey': 'TRY',
  'russia': 'RUB', 'poland': 'PLN', 'czechia': 'CZK', 
  'hungary': 'HUF', 'romania': 'RON', 'ukraine': 'UAH',
  'israel': 'ILS', 'chile': 'CLP', 'colombia': 'CO$',
  'argentina': 'ARS', 'peru': 'PEN', 'algeria': 'DZD',
  'ethiopia': 'ETB', 'bahrain': 'BHD', 'oman': 'OMR',
  'jordan': 'JOD', 'georgia': 'GEL', 'kazakhstan': 'KZT',
  'bulgaria': 'BGN', 'iceland': 'ISK', 'botswana': 'BWP',
  'zambia': 'ZMW', 'rwanda': 'RWF',
};